services:
  - type: web
    name: your-app-name
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
